#! /usr/bin/env bash

if [ -n "${AM_PROMPT_BASH:-}" ]; then
	return
fi

printf "\n%s\n" "prompt: using bash shell"

if [ -f "$HOME"/.am/prompt/sh/profile ]; then
	. "$HOME"/.am/prompt/sh/profile
fi

if [ -f "$HOME"/.am/prompt/bash/bashrc ]; then
	. "$HOME"/.am/prompt/bash/bashrc
fi

AM_PROMPT_BASH=1
