branches:
  - master
  - +([0-9])?(.{+([0-9]),x}).x
  - name: next
    prerelease: true

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - path: "@semantic-release/exec"
    prepareCmd: echo ${nextRelease.gitHead} > VERSION
  - path: "@semantic-release/github"
  - path: "@semantic-release/git"
    assets:
      - CHANGELOG.md
      - VERSION
