plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"

branches:
  - master
  - release/*
  - name: next
    prerelease: true
