#!/usr/bin/env bash

__am-prompt-edit-vars() {
    local VAR_PATH="$AM_PROMPT/user/variables"

    if [ ! -f "$VAR_PATH" ]; then
        echo "#!/usr/bin/env bash" > "$VAR_PATH"
        echo >> "$VAR_PATH"
    fi

    ${EDITOR:-vi} "$VAR_PATH"
}

__am-prompt-edit-vars
