#!/usr/bin/env bash

__am-prompt-git-token() {
    local GH_TOKEN=$1

    if [ -z ${GH_TOKEN:-} ]; then
        echo 'usage: git-token [token]'
    else
        add-var GH_TOKEN $GH_TOKEN
    fi
}

__am-prompt-git-token $@
