#!/usr/bin/env bash

minikube config set cpus 4
minikube config set memory 4096
minikube config set bootstrapper kubeadm
minikube config set kubernetes-version 1.15.5

# enable the dashboard and heapter
minikube config set dashboard true
minikube config set heapster true

# make sure ingress is off
minikube config set ingress false

# detect missing psp
if [ ! -f "$HOME/.minikube/addons/psp.yaml" ]; then

    # get default pod security policy
    curl -L https://github.com/kubernetes/minikube/files/3065532/psp.txt -o $HOME/.minikube/addons/psp.yaml
fi

# start minikube
minikube-start
