#!/usr/bin/env bash

__am-prompt-remove-backup() {
    local BACKUP=$1

    if [ -z ${BACKUP:-} ]; then
        BACKUP='prompt'
    fi

    local REMOVE_PATH="$AM_HOME/backup/$BACKUP"

    echo "removing path: $REMOVE_PATH..."
    rm -rf "$AM_HOME/backup/$BACKUP" 2>/dev/null
}

__am-prompt-remove-backup $@
