#!/usr/bin/env bash

__am-prompt-update-prompt() {
    local SHA_PATH=$HOME/.am/prompt/.sha
    local SHA=$(git-sha)

    if [ "${1:-}" = "--force" ]; then
        rm -rf $SHA_PATH 1>/dev/null 2>&1
    fi

    if [ -f ${SHA_PATH:-} ]; then
        local CURRENT_SHA=$(cat $SHA_PATH)

        if [ -z ${SHA:-} ]; then
            echo -e "${CLR_FAIL}prompt: cannot retrieve SHA of latest version. Are you connected to the internet?${CLR_CLEAR}"
            return 1
        fi

        if [ "${SHA:-}" = "${CURRENT_SHA:-}" ]; then
            echo -e "${CLR_SUCCESS}prompt: latest version already installed: ${SHA}.${CLR_CLEAR}"
            return 0
        fi
    fi

    if [ "${1:-}" = "--dry-run" ]; then
        echo -e "${CLR_WARN}prompt: a new version of prompt is available: ${SHA}."
        echo -e "  - run the update-prompt command line tool to upgrade${CLR_CLEAR}"
        return 0
    fi

    remove-backup

    local CHANGELOG_URI="https://github.com/automotivemastermind/prompt/blob/master/CHANGELOG.md"
    local UPDATE_URI="https://github.com/automotivemastermind/prompt/archive/master.tar.gz"
    local UPDATE_TEMP=$(mktemp -d)

    pushd "$UPDATE_TEMP" 1>/dev/null
    curl -skL $UPDATE_URI | tar zx
    pushd prompt-master 1>/dev/null
    ./install.sh
    popd 1>/dev/null
    popd 1>/dev/null

    rm -rf "$UPDATE_TEMP" 1>/dev/null

    open-url $CHANGELOG_URI 1>/dev/null
}

__am-prompt-update-prompt $@
