#!/usr/bin/env bash

# install the hypervisor
sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils

# set the vm-driver
minikube config set vm-driver kvm2

# setup minikube
minikube-setup
