version: 2

jobs:
  macos:
    macos:
      xcode: "11.2.1"
    steps:
      - checkout
      - run:
          name: test
          command: ./test.sh
      - run:
          name: install-bash
          command: ./install.sh bash | tee log.txt && bash -lc "git sha"
      - run:
          name: install-zsh
          command: ./install.sh zsh | tee -a log.txt && zsh -lc "git sha"
      - store_artifacts:
          path: log.txt
          destination: logs/$CIRCLE_STAGE.txt

  ubuntu:
    docker:
      - image: docker:stable
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: install and verify
          command: docker build --file docker/$CIRCLE_STAGE/Dockerfile . | tee log.txt
      - store_artifacts:
          path: log.txt
          destination: logs/$CIRCLE_STAGE.txt

  debian:
    docker:
      - image: docker:stable
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: install and verify
          command: docker build --file docker/$CIRCLE_STAGE/Dockerfile . | tee log.txt
      - store_artifacts:
          path: log.txt
          destination: logs/$CIRCLE_STAGE.txt

  fedora-29:
    docker:
      - image: docker:stable
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: install and verify
          command: docker build --file docker/$CIRCLE_STAGE/Dockerfile . | tee log.txt
      - store_artifacts:
          path: log.txt
          destination: logs/$CIRCLE_STAGE.txt

  fedora-30:
    docker:
      - image: docker:stable
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: install and verify
          command: docker build --file docker/$CIRCLE_STAGE/Dockerfile . | tee log.txt
      - store_artifacts:
          path: log.txt
          destination: logs/$CIRCLE_STAGE.txt

  fedora-31:
    docker:
      - image: docker:stable
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: install and verify
          command: docker build --file docker/$CIRCLE_STAGE/Dockerfile . | tee log.txt
      - store_artifacts:
          path: log.txt
          destination: logs/$CIRCLE_STAGE.txt

  centos:
    docker:
      - image: docker:stable
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: install and verify
          command: docker build --file docker/$CIRCLE_STAGE/Dockerfile . | tee log.txt
      - store_artifacts:
          path: log.txt
          destination: logs/$CIRCLE_STAGE.txt

  mint:
    docker:
      - image: docker:stable
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: install and verify
          command: docker build --file docker/$CIRCLE_STAGE/Dockerfile . | tee log.txt
      - store_artifacts:
          path: log.txt
          destination: logs/$CIRCLE_STAGE.txt

  deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a0:dd:b4:96:be:95:30:89:5e:a4:67:57:98:ba:c2:da"
      - checkout
      - restore_cache:
          name: restore yarn package cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: publish
          command: ./publish.sh
      - save_cache:
          name: save yarn package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

workflows:
  version: 2
  install:
    jobs:
      - macos:
          filters:
            branches:
              ignore: master
      - ubuntu:
          filters:
            branches:
              ignore: master
      - debian:
          filters:
            branches:
              ignore: master
      - fedora-29:
          filters:
            branches:
              ignore: master
      - fedora-30:
          filters:
            branches:
              ignore: master
      - fedora-31:
          filters:
            branches:
              ignore: master
      - centos:
          filters:
            branches:
              ignore: master
      - mint:
          filters:
            branches:
              ignore: master
      - deploy:
          filters:
            branches:
              only: master
