#!/usr/bin/env sh

__am_prompt_add_bookmark_usage() {
    echo 'add-bookmark <name>'
    echo '     name : a name for your bookmark'
}

__am_prompt_add_bookmark() {
    # make sure that a bookmark was specified.
    if [ -z ${1:-} ]; then
        echo 'add-bookmark: missing <name>'
        $1="--help"
    fi

    if [ "${1:-}" = "--help" ]; then
        __am_prompt_add_bookmark_usage
        return
    fi

    # make sure we remove any existing bookmark before defining another one.
    remove-bookmark $1 silent
    local BOOKMARK="$1"=\"$(pwd)\"

    echo "add-bookmark: adding bookmark $BOOKMARK"
    echo $BOOKMARK >> "$HOME/.am/prompt/user/bookmarks.sh"
    . "$HOME/.am/prompt/user/bookmarks.sh"
}

__am_prompt_add_bookmark $@
