#! /usr/bin/env sh

__am_prompt_add_var_usage() {
	printf "%s\n" "[add-var|set-var] <name> <value>"
	printf "\t%s\n" \
		"name  : a name for your variable" \
		"value : a value for your variable"
}

__am_prompt_add_var() {
	# make sure that a bookmark was specified.
	if [ -z "${1:-}" ]; then
		printf "%s\n" "add-var: missing <name>"
		__am_prompt_add_var_usage
		return
	fi

	if [ "${1:-}" = "--help" ]; then
		__am_prompt_add_var_usage
		return
	fi

	if [ -z "${2:-}" ]; then
		printf "%s\n" "add-var: missing <value>"
		__am_prompt_add_var_usage
		return
	fi

	# make sure we remove any existing variable before defining another one
	remove-var "$1" silent
	VARIABLE="$1"=\"$2\"
	VAR_PATH="$AM_PROMPT/user/variables.sh"

	printf "%s\n" "add-var: adding varable: $VARIABLE"
	printf "\n%s\n" "$VARIABLE" >> "$VAR_PATH"
	. "$VAR_PATH"
}

__am_prompt_add_var "$@"
