#! /usr/bin/env sh

__am_prompt_add_var_usage() {
	print-warn "[add-var|set-var] <name> <value>" \
		"	name  : a name for your variable" \
		"	value : a value for your variable"
}

__am_prompt_add_var() {

	# capture the name
	name=${1:-}
	shift

	# capture the remainder as a value
	value=${*:-}

	if [ -z "$name" ]; then
		print-warn "add-var: missing <name>"
		__am_prompt_add_var_usage
		return
	fi

	if [ "$name" = "--help" ]; then
		__am_prompt_add_var_usage
		return
	fi

	if [ -z "$value" ]; then
		print-warn "add-var: missing <value>"
		__am_prompt_add_var_usage
		return
	fi

	# remove the var if it currently exists
	remove-var "$name" --silent
	VAR_PATH="$AM_PROMPT/user/variables"
	key="$name=\"$value\""

	printf "export %s\n" "$key" >> "$VAR_PATH"
	print-success "add-var: successfully added value for $key" \
		"start a new shell or reload the variables using:" \
		". \"$VAR_PATH\""
}

__am_prompt_add_var "$@"
