#!/usr/bin/env sh

__am_prompt_add_var_usage() {
    echo '[add-var|set-var] <name> <value>'
    echo '     name  : a name for your variable'
    echo '     value : a value for your variable'
}

__am_prompt_add_var() {
    # make sure that a bookmark was specified.
    if [ -z ${1:-} ]; then
        echo 'add-var: missing <name>'
        __am_prompt_add_var_usage
        return
    fi

    if [ "${1:-}" = "--help" ]; then
        __am_prompt_add_var_usage
        return
    fi

    if [ -z ${2:-} ]; then
        echo 'add-var: missing <value>'
        __am_prompt_add_var_usage
        return
    fi

    # make sure we remove any existing variable before defining another one
    remove-var $1 silent
    local VARIABLE="$1"=\"$2\"
    local VAR_PATH="$AM_PROMPT/user/variables.sh"

    echo "add-var: adding varable: $VARIABLE"
    echo >> "$VAR_PATH"
    echo "$VARIABLE" >> "$VAR_PATH"
    source "$VAR_PATH"
}

__am_prompt_add_var $@
