#! /usr/bin/env sh

__am_prompt_edit_vars() {
	VAR_PATH="$AM_PROMPT/user/variables"

	if [ ! -f "$VAR_PATH" ]; then
		printf "%s\n\n" "#! /usr/bin/env sh" > "$VAR_PATH"
	fi

	"${EDITOR:-vi}" "$VAR_PATH"
}

__am_prompt_edit_vars
