#!/usr/bin/env sh

__am_prompt_git_token() {
    local GH_TOKEN=$1

    if [ -z ${GH_TOKEN:-} ]; then
        echo 'usage: git-token [token]'
    else
        add-var GH_TOKEN $GH_TOKEN
    fi
}

__am_prompt_git_token $@
