#!/usr/bin/env sh

__am_prompt_git_release() {

    local ORG_NAME=${1:-'automotivemastermind'}
    local REPO_NAME=${2:-'prompt'}

    local CURL_OPT='-s'

    if [ ! -z "${GITHUB_TOKEN:-}" ]; then
        CURL_OPT="$CURL_OPT -H 'Authorization: $GITHUB_TOKEN'"
    fi

    local RELEASE_URI=https://api.github.com/repos/$ORG_NAME/$REPO_NAME/releases/latest
    local RELEASE=$(curl $CURL_OPT $RELEASE_URI | grep tag_name | head -n 1 | sed 's#.*\:.*"\(.*\).*",#\1#')

    if [ ! -z "${RELEASE:-}" ]; then
        echo $RELEASE
        return 0
    fi

    return 1
}

__am_prompt_git_release $@
