#! /usr/bin/env sh

__am_prompt_git_release() {

	ORG_NAME=${1:-'automotivemastermind'}
	REPO_NAME=${2:-'prompt'}

	if [ -n "${GITHUB_TOKEN:-}" ]; then
		set -- -H "Authorization: $GITHUB_TOKEN"
	fi

	RELEASE_URI=https://api.github.com/repos/$ORG_NAME/$REPO_NAME/releases/latest
	RELEASE=$(curl -s "$@" "$RELEASE_URI" | grep tag_name | head -n 1 | sed 's#.*\:.*"\(.*\).*",#\1#')

	if [ -n "${RELEASE:-}" ]; then
		printf "%s\n" "$RELEASE"
		return 0
	fi

	return 1
}

__am_prompt_git_release "$@"
