#!/usr/bin/env sh

__am_prompt_git_token() {
    local GITHUB_TOKEN=$1

    if [ -z ${GITHUB_TOKEN:-} ]; then
        echo 'usage: git-token [token]'
    else
        add-var GITHUB_TOKEN $GITHUB_TOKEN
    fi
}

__am_prompt_git_token $@
