#! /usr/bin/env sh

__am_prompt_git_sha() {

	ORG_NAME=$1
	REPO_NAME=$2
	BRANCH_NAME=$3

	if [ -z "${ORG_NAME:-}" ]; then
		ORG_NAME='automotivemastermind'
	fi

	if [ -z "${REPO_NAME:-}" ]; then
		REPO_NAME='prompt'
	fi

	if [ -z "${BRANCH_NAME:-}" ]; then
		BRANCH_NAME='master'
	fi

	if [ -n "${GITHUB_TOKEN:-}" ]; then
		set -- -H "Authorization: $GITHUB_TOKEN"
	fi

	SHA_URI=https://api.github.com/repos/$ORG_NAME/$REPO_NAME/commits/$BRANCH_NAME
	SHA=$(curl -s "$@" $SHA_URI | grep sha | head -n 1 | sed 's#.*\:.*"\(.*\).*",#\1#')

	if [ -n "${SHA:-}" ]; then
		printf "%s\n" "$SHA"
		return
	fi

	return 1
}

__am_prompt_git_sha "$@"
