#! /usr/bin/env sh

__am_prompt_aws_install() {

	if command -v aws 1>/dev/null 2>&1; then
		return
	fi

	temp=$(mktemp -d)
	platform=$(uname | tr "[:upper:]" "[:lower:]")
	arch=$(uname -m)

	print-success "downloading aws-sdk..."
	curl -Lso "$temp"/aws.zip https://awscli.amazonaws.com/awscli-exe-"$platform"-"$arch".zip

	# extract the contents
	(cd "$temp" && unzip aws.zip)

	# run the installer
	print-success "installing aws-sdk..."
	"$temp"/aws/install --install-dir "$AM_PROMPT_USER"/aws --bin-dir "$AM_PROMPT_USER"/bin

	# remove the temp path
	rm -rf "$temp"

	# print a warning about restarting
	print-warn '' 'start a new shell to enable tab completion...'
}

__am_prompt_aws_install
