#! /usr/bin/env sh

__am_prompt_gcloud_install() {

	version="323.0.0"

	while :; do
		case $1 in
			-v|--version)
				version=$2
				shift
				;;
			-f|--force)
				if [ -d "$HOME"/.gcloud ]; then
					rm -rf "$HOME"/.gcloud 1>/dev/null
				fi

				if [ -d "$AM_PROMPT_USER"/bin/gcloud ]; then
					rm -rf "$HOME"/gcloud 1>/ev/null
				fi
				;;
			--debug)
				set -x
				;;
			?*)
				print-fail "install-gcloud: invalid argument: $1"
				;;
			*)
				break
				;;
		esac
		shift
	done

	if command -v gcloud 1>/dev/null 2>&1; then
		return
	fi

	temp="$(mktemp -d 2>/dev/null || mktemp -d -t 'mytmpdir')"
	platform=$(uname | tr "[:upper:]" "[:lower:]")
	arch=$(uname -m)

	print-success "downloading gcloud-sdk..."
	curl -Lso "$temp"/gcloud.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-"$version"-"$platform"-"$arch".tar.gz

	# tar will fail if the directory doesn't exist
	if [ ! -d "$AM_PROMPT_USER"/bin/gcloud ]; then
		mkdir "$AM_PROMPT_USER"/bin/gcloud
	fi

	# extract the executable
	tar -xf "$temp"/gcloud.tar.gz --strip-components=1 --directory="$AM_PROMPT_USER"/bin/gcloud  1>/dev/null

	# remove the temp directory
	rm -rf "$temp"

	# run the installer
	print-success "installing gcloud-sdk..."
	"$AM_PROMPT_USER"/bin/gcloud/install.sh \
		--command-completion false \
		--usage-reporting false \
		--quiet \
		--path-update false \
		--additional-components kubectl gsutil core 2>&1

	# setup completion
	if [ -f "$AM_PROMPT_USER"/gcloud/completion.bash.inc ]; then
		ln -fs \
			"$AM_PROMPT_USER"/gcloud/completion.bash.inc \
			"$AM_PROMPT_USER"/bash/completions/gcloud.inc
	fi

	if [ -f "$AM_PROMPT_USER"/gcloud/completion.zsh.inc ]; then
		ln -fs \
			"$AM_PROMPT_USER"/gcloud/completion.zsh.inc \
			"$AM_PROMPT_USER"/zsh/completions/_gcloud
	fi

	# print a warning about restarting
	print-warn '' 'start a new shell to enable tab completion...'
}

__am_prompt_gcloud_install "$@"
