#! /usr/bin/env sh

__am_prompt_gcloud_install() {
	GCLOUD_PATH="$HOME/.gcloud"
	PLATFORM='linux'

	if [ "$(uname)" = "Darwin" ]; then
		PLATFORM='darwin'
	fi

	URL=https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-161.0.0-$PLATFORM-x86_64.tar.gz

	TEMP=$(mktemp -d)
	FILENAME="$TEMP/gcloud-sdk.tar.gz"
	EXPANDED="$TEMP/google-cloud-sdk"

	if ! command -v gcloud 1>/dev/null 2>&1; then

		print-success "downloading gcloud-sdk..."
		curl -L $URL -o "$FILENAME" --silent 2>&1

		tar -xf "$FILENAME" -C "$TEMP" 1>/dev/null 2>&1

		rm -rf "$GCLOUD_PATH" 1>/dev/null 2>&1
		mv "$EXPANDED" "$GCLOUD_PATH" 1>/dev/null 2>&1
		rm -rf "$TEMP" 1>/dev/null 2>&1

		print-success "installing gcloud-sdk..."
		"$HOME"/.gcloud/install.sh --command-completion false --usage-reporting false --quiet --path-update false 2>&1

		GCLOUD_PATH_INC="$HOME"/.gcloud/path.bash.inc

		if [ -f "$GCLOUD_PATH_INC" ]; then
			. "$GCLOUD_PATH_INC"
		fi
	fi

	print-success "installing and updating gcloud components..."
	gcloud components install kubectl gsutil core --quiet 2>&1
	gcloud components update --quiet 2>&1
}

__am_prompt_gcloud_install
