#! /usr/bin/env sh

__am_kind_prompt_install() {

	# determine if kind is already available
	if command -v kind 1>/dev/null 2>&1; then

		# move on immediately
		return 0
	fi

	# install kind with homebrew now that its available there
	brew install kind
}

__am_kind_prompt_install
