#! /usr/bin/env sh

if ! command -v print-warn 1>/dev/null 2>&1; then
	. "$HOME"/.am/prompt/sh/scripts/eval/set-colors
fi

__am_prompt_open_url() {
	url=${1:-}

	if [ -z "$url" ]; then
		print-fail "open-url: url must be supplied"
		return 1
	fi

	for cmd in open gnome-open kde-open xdg-open sensible-browser; do
		if command -v $cmd 1>/dev/null 2>&1; then
			print-success "open-url: opening $url via $cmd..."
			$cmd "$url" 1>/dev/null 2>&1

			if ! $cmd "$url" 1>/dev/null 2>&1; then
				print-warn "open-url: please open a browser to: $url"
			fi

			return 0
		fi
	done

	# no open or browser was available (headless)
	print-warn "open-url: please open a browser to: $url"
}

__am_prompt_open_url "$@"
