#!/usr/bin/env sh

__am_prompt_remove_backup() {
    local BACKUP=$1

    if [ -z "${BACKUP:-}" ]; then
        BACKUP='prompt'
    fi

    local REMOVE_PATH="$AM_HOME/backup/$BACKUP"

    echo "removing path: $REMOVE_PATH..."
    rm -rf "$AM_HOME/backup/$BACKUP" 2>/dev/null
}

__am_prompt_remove_backup $@
