#! /usr/bin/env sh

set -e

__am_prompt_remove_var_usage() {
	printf "%s\n\t%s\n" \
		"remove-var <name>" \
			"name : a name for your variable"
}

__am_prompt_remove_var() {
	VARIABLE=$1
	REMOVE=
	USER_PATH="$AM_PROMPT/user"
	VAR_PATH="$USER_PATH/variables"

	if [ -z "${VARIABLE:-}" ]; then
		__am_prompt_remove_var_usage
		return 1
	fi

	REMOVE=$(grep -s -m 1 ^"export $VARIABLE=" "$VAR_PATH")

	if [ -z "${REMOVE:-}" ]; then
		printf "%s\n" "remove-var: no variable was declared for the specified name"

		return 1
	fi

	printf "%s\n" "remove-var: removing variable $REMOVE"

	unset "$VARIABLE" 1>/dev/null 2>&1
	grep -s -v ^"export $VARIABLE=" "$VAR_PATH" >> "$USER_PATH/variables1"
	mv -f "$USER_PATH/variables1" "$USER_PATH/variables"

	print-success "remove-var: successfully removed value for $VARIABLE" \
		"start a new shell or unset the variable using:" \
		"unset $VARIABLE"
}

__am_prompt_remove_var "$@"
