#! /usr/bin/env sh

set -e

__am_prompt_remove_backup() {
	BACKUP=$1

	if [ -z "${BACKUP:-}" ]; then
		BACKUP='prompt'
	fi

	REMOVE_PATH="$AM_HOME/backup/$BACKUP"

	print-warn "removing path: $REMOVE_PATH..."
	rm -rf "$AM_HOME/backup/$BACKUP" 2>/dev/null
}

__am_prompt_remove_backup "$@"
