#! /usr/bin/env sh

__am_prompt_remove_var_usage() {
	printf "%s\n\t%s\n" \
		"remove-var <name>" \
			"name : a name for your variable"
}

__am_prompt_remove_var() {
	VARIABLE=$1
	REMOVE=
	USER_PATH="$AM_PROMPT/user"
	VAR_PATH="$USER_PATH/variables"

	if [ -z "${VARIABLE:-}" ]; then
		__am_prompt_remove_var_usage
		return 1
	fi

	REMOVE=$(grep -s -m 1 ^"$VARIABLE" "$VAR_PATH")
	unset "$VARIABLE" 1>/dev/null 2>&1

	if [ -z "${REMOVE:-}" ]; then
		printf "%s\n" "remove-var: no variable was declared for the specified name"

		return 1
	fi

	printf "%s\n" "remove-var: removing variable $REMOVE"

	grep -s -v ^"$VARIABLE" "$VAR_PATH" >> "$USER_PATH/variables1"
	mv -f "$USER_PATH/variables1" "$USER_PATH/variables"

	. "$USER_PATH/variables"
}

__am_prompt_remove_var "$@"
