#! /usr/bin/env sh

__am_prompt_reverse() {
	reversed=

	# shellcheck disable=SC2068
	for value in $@; do
		reversed="$value $reversed"
	done

	printf '%s' "${reversed%*' '}"
}

__am_prompt_reverse "$@"
