#!/usr/bin/env sh

__am_prompt_show_vars() {
    local VAR_PATH="$HOME/.am/prompt/user/variables.sh"

    if [ ! -f $VAR_PATH ]; then
        echo 'show-vars: no variables are currently specified'
        add-var-usage
        return
    fi

    cat $VAR_PATH
}

__am_prompt_show_vars
