#!/usr/bin/env sh

echo

for color in $(env | awk '/^CLR_BRIGHT/' | cut -d= -f1 | sort); do
    echo "${!color}\$$color${CLR_CLEAR}"
done

echo

for color in $(env | awk '/^CLR_/' | awk '!/^CLR_BRIGHT/' | awk '!/_PROMPT/' | cut -d= -f1 | sort); do
    echo "${!color}\$$color${CLR_CLEAR}"
done

echo

for color in $(env | awk '/^CLR/' | awk '/_PROMPT/' | cut -d= -f1 | sort); do
    echo "${!color}\$$color${CLR_CLEAR}"
done
