#! /usr/bin/env sh

set -e

if [ -z "${GNOME_TERMINAL_SERVICE:-}" ]; then
	print-fail "themes are only supported for gnome terminal"
	exit 1
fi

PROMPT_THEME_NAME=${1:-"dark-mode"}
PROMPT_THEME=$HOME/.am/prompt/themes/linux/$PROMPT_THEME_NAME.theme

if [ ! -f "${PROMPT_THEME:-}" ]; then
	print-fail "the theme $PROMPT_THEME_NAME is not supported"
	exit 1
fi

DEFAULT_PROFILE=$(dconf read /org/gnome/terminal/legacy/profiles:/default)
DEFAULT_PROFILE=${DEFAULT_PROFILE:-$(gsettings get org.gnome.Terminal.ProfilesList default)}
DEFAULT_PROFILE=${DEFAULT_PROFILE#\'}
DEFAULT_PROFILE=${DEFAULT_PROFILE%\'}
DEFAULT_PROFILE=${DEFAULT_PROFILE:-"b1dcc9dd-5262-4d8d-a863-c897e6d979b9"}

# load the theme file
dconf load "/org/gnome/terminal/legacy/profiles:/:$DEFAULT_PROFILE/" < "$PROMPT_THEME"
dconf write /org/gnome/terminal/legacy/profiles:/default "'$DEFAULT_PROFILE'"
gsettings set org.gnome.Terminal.ProfilesList default "'$DEFAULT_PROFILE'"
