#!/usr/bin/env sh

__contains() { for item in "${@:2}"; do [[ "$item" == "$1" ]] && return 0; done; return 1; }

SOLUTIONS=($@)

CURRENT_DIR=${PWD}

if [ ${#SOLUTIONS[@]} -eq 0 ]; then
    SOLUTIONS=(*.sln)
fi

for solution in "${SOLUTIONS[@]}"; do
    if [ ! -f "$solution" ]; then
        echo "ERROR: $solution does not exist; skipping..."
        echo

        continue
    fi

    solution="./$solution"

    basepath="${solution%/*}"
    name="${solution##*/}"

    echo "Checking solution: $name"

    cd "$basepath" 1>/dev/null

    EXISTING=($(dotnet sln "$name" list))
    EXISTING=("${EXISTING[@]:2}")
    DISCOVERED=($(find * -name '*.csproj' ! -path '*/bin/*' ! -path '*/obj/*' ! -path '*/shared/*' ))

    for existing in "${EXISTING[@]}"; do
        __contains $existing "${DISCOVERED[@]}" || dotnet sln "$name" remove "$existing"
    done

    for discovered in "${DISCOVERED[@]}"; do
        __contains $discovered "${EXISTING[@]}" || dotnet sln "$name" add "$discovered"
    done

    cd $CURRENT_DIR
done
