#!/usr/bin/env sh

# set globals for colors
export CLR_CLEAR='\033[0m'              # DEFAULT COLOR

export CLR_BLACK='\033[0;30m'           # ANSI BLACK (GRAY)
export CLR_RED='\033[0;31m'             # ANSI RED
export CLR_GREEN='\033[0;32m'           # ANSI GREEN
export CLR_YELLOW='\033[0;33m'          # ANSI YELLOW
export CLR_BLUE='\033[0;34m'            # ANSI BLUE
export CLR_MAGENTA='\033[0;35m'         # ANSI MAGENTA (PURPLE)
export CLR_CYAN='\033[0;36m'            # ANSI CYAN
export CLR_WHITE='\033[0;37m'           # ANSI WHITE

export CLR_BRIGHT_BLACK='\033[1;30m'    # BRIGHT BLACK (GRAY)
export CLR_BRIGHT_RED='\033[1;31m'      # BRIGHT RED
export CLR_BRIGHT_GREEN='\033[1;32m'    # BRIGHT GREEN
export CLR_BRIGHT_YELLOW='\033[1;33m'   # BRIGHT YELLOW
export CLR_BRIGHT_BLUE='\033[1;34m'     # BRIGHT BLUE
export CLR_BRIGHT_MAGENTA='\033[1;35m'  # BRIGHT MAGENTA (PURPLE)
export CLR_BRIGHT_CYAN='\033[1;36m'     # BRIGHT CYAN
export CLR_BRIGHT_WHITE='\033[1;37m'    # BRIGHT WHITE

# determine if this is not a tty
if [ ! -t 1 ]; then

    # wipe out all of the colors
    export CLR_CLEAR=''
    export CLR_BLACK=''
    export CLR_RED=''
    export CLR_GREEN=''
    export CLR_YELLOW=''
    export CLR_BLUE=''
    export CLR_MAGENTA=''
    export CLR_CYAN=''
    export CLR_WHITE=''
    export CLR_BRIGHT_BLACK=''
    export CLR_BRIGHT_RED=''
    export CLR_BRIGHT_GREEN=''
    export CLR_BRIGHT_YELLOW=''
    export CLR_BRIGHT_BLUE=''
    export CLR_BRIGHT_MAGENTA=''
    export CLR_BRIGHT_CYAN=''
    export CLR_BRIGHT_WHITE=''
else
    # enable colors for various commands
    export TERM=xterm-256color
    export GREP_COLOR='1;32'
    export CLICOLOR=1
    alias grep="grep --color=auto"

    # change ls colors to be more like original unix/linux
    export LSCOLORS="ExGxBxDxCxEgEdxbxgxcxd"
fi

export CLR_SUCCESS=$CLR_BRIGHT_GREEN    # COLOR FOR SUCCESS MESSAGES
export CLR_FAIL=$CLR_BRIGHT_RED         # COLOR FOR ERROR MESSAGES
export CLR_WARN=$CLR_BRIGHT_YELLOW      # COLOR FOR WARNING MESSAGES
export CLR_RESET=$CLR_CLEAR             # ALIAS FOR CLEAR COLOR

export CLR_ROOT_PROMPT=$CLR_BRIGHT_RED    # COLOR OF THE PROMPT FOR ROOT
export CLR_STAFF_PROMPT=$CLR_BRIGHT_GREEN # COLOR OF THE PROMPT FOR STAFF
export CLR_USER_PROMPT=$CLR_BRIGHT_BLUE   # COLOR OF THE PROMPT FOR USERS
export CLR_SSH_PROMPT=$CLR_BRIGHT_MAGENTA # COLOR OF THE PROMPT FOR SSH

# use code as the default editor
if type code 1>/dev/null 2>&1; then
    export EDITOR='code --wait'
fi

export HISTCONTROL=ignoredubs

# detect the apple silicon brew path
if [ -f /opt/homebrew/bin/brew ]; then

    # force update the path
    export PATH="/opt/homebrew/bin:$PATH"
fi

if type brew 1>/dev/null 2>&1; then
    export LOCAL_PREFIX=$(brew --prefix)
elif [ -d $LOCALAPPDATA/git ]; then
    export LOCAL_PREFIX=$(echo "/$LOCALAPPDATA/git" | sed -e 's/\\/\//g' -e 's/://')
else
    export LOCAL_PREFIX=/usr/local
fi

# add am home
export AM_HOME="$HOME/.am"
export AM_PROMPT="$AM_HOME/prompt"

# add scripts to path
export PATH="$AM_PROMPT/sh/scripts:$PATH"

# test for user variables
if [ -f $AM_PROMPT/user/variables ]; then
    . "$AM_PROMPT/user/variables"
fi

# test for prompt bin
if [ -d "$AM_PROMPT/user/bin" ]; then
    # append prompt to path
    export PATH="$AM_PROMPT/user/bin:$PATH"
fi

# evaluate eval scripts
for EVAL_SCRIPT in $AM_PROMPT/sh/scripts/eval/*; do
    . "$EVAL_SCRIPT"
done

# aliases
# -- prompt for overwrites
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

# -- DOS-style shortcuts
alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd .. ; ..'

# -- sudo alias (allow other alias extensions to work when sudo-ing)
alias sudo='sudo '
