#! /usr/bin/env sh

if [ -t 1 ]; then
	# enable colors for various commands
	export TERM=xterm-256color
	export GREP_COLOR='1;32'
	export CLICOLOR=1
	alias grep="grep --color=auto"

	# change ls colors to be more like original unix/linux
	export LSCOLORS="ExGxBxDxCxEgEdxbxgxcxd"
fi

# use code as the default editor
if command -v code 1>/dev/null 2>&1; then
	export EDITOR='code --wait'
fi

# detect the apple silicon brew path
if [ -f /opt/homebrew/bin/brew ]; then

	# force update the path
	export PATH="/opt/homebrew/bin:$PATH"
fi

if command -v brew 1>/dev/null 2>&1; then
	LOCAL_PREFIX=$(brew --prefix)
elif [ -d "$LOCALAPPDATA"/git ]; then
	LOCAL_PREFIX=$(printf "%s" "/$LOCALAPPDATA/git" | sed -e 's/\\/\//g' -e 's/://')
else
	LOCAL_PREFIX=/usr/local
fi

# export the prefix
export LOCAL_PREFIX

# add am home
export AM_HOME="$HOME/.am"
export AM_PROMPT="$AM_HOME/prompt"

# add scripts to path
export PATH="$AM_PROMPT/sh/scripts:$PATH"

# test for user variables
if [ -f "$AM_PROMPT"/user/variables ]; then
	. "$AM_PROMPT"/user/variables
fi

# test for prompt bin
if [ -d "$AM_PROMPT"/user/bin ]; then
	# append prompt to path
	export PATH="$AM_PROMPT/user/bin:$PATH"
fi

# evaluate eval scripts
for EVAL_SCRIPT in "$AM_PROMPT"/sh/scripts/eval/*; do
	. "$EVAL_SCRIPT"
done

# aliases
# -- prompt for overwrites
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

# -- DOS-style shortcuts
alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd .. ; ..'

# -- sudo alias (allow other alias extensions to work when sudo-ing)
alias sudo='sudo '
