#! /usr/bin/env sh

# source the os release
. /etc/os-release

# get the major version
MAJOR_VERSION=${VERSION_ID%.*}

sudo apt-get update -y

case "${MAJOR_VERSION}" in
	"9")
		sudo apt-get install -y --no-install-recommends \
			ca-certificates \
			\
			libc6 \
			libgcc1 \
			libgssapi-krb5-2 \
			libicu57 \
			liblttng-ust0 \
			libssl1.0.2 \
			libstdc++6 \
			zlib1g
		;;
	"10")
		sudo apt-get install -y --no-install-recommends \
			ca-certificates \
			\
			libc6 \
			libgcc1 \
			libgssapi-krb5-2 \
			libicu63 \
			libssl1.1 \
			libstdc++6 \
			zlib1g
		;;
esac
