#! /usr/bin/env bash

__am_prompt_edit_bashrc() {
	BASHRC_PATH="$AM_PROMPT/user/bashrc"

	if [ ! -f "$BASHRC_PATH" ]; then
		printf "%s\n\n" "#! /usr/bin/env bash" > "$BASHRC_PATH"
	fi

	${EDITOR:-vi} "$BASHRC_PATH"
}

__am_prompt_edit_bashrc
