#!/usr/bin/env bash

__am_prompt_edit_bashrc() {
    local BASHRC_PATH="$AM_PROMPT/user/bashrc"

    if [ ! -f "$BASHRC_PATH" ]; then
        echo "#!/usr/bin/env bash" > "$BASHRC_PATH"
        echo >> "$BASHRC_PATH"
    fi

    ${EDITOR:-vi} "$BASHRC_PATH"
}

__am_prompt_edit_bashrc
