# set globals for colors
export CLR_CLEAR='\033[0m'              # DEFAULT COLOR

export CLR_BLACK='\033[0;30m'           # ANSI BLACK (GRAY)
export CLR_RED='\033[0;31m'             # ANSI RED
export CLR_GREEN='\033[0;32m'           # ANSI GREEN
export CLR_YELLOW='\033[0;33m'          # ANSI YELLOW
export CLR_BLUE='\033[0;34m'            # ANSI BLUE
export CLR_MAGENTA='\033[0;35m'         # ANSI MAGENTA (PURPLE)
export CLR_CYAN='\033[0;36m'            # ANSI CYAN
export CLR_WHITE='\033[0;37m'           # ANSI WHITE

export CLR_BRIGHT_BLACK='\033[1;30m'    # BRIGHT BLACK (GRAY)
export CLR_BRIGHT_RED='\033[1;31m'      # BRIGHT RED
export CLR_BRIGHT_GREEN='\033[1;32m'    # BRIGHT GREEN
export CLR_BRIGHT_YELLOW='\033[1;33m'   # BRIGHT YELLOW
export CLR_BRIGHT_BLUE='\033[1;34m'     # BRIGHT BLUE
export CLR_BRIGHT_MAGENTA='\033[1;35m'  # BRIGHT MAGENTA (PURPLE)
export CLR_BRIGHT_CYAN='\033[1;36m'     # BRIGHT CYAN
export CLR_BRIGHT_WHITE='\033[1;37m'    # BRIGHT WHITE

export CLR_ROOT_PROMPT=$CLR_BRIGHT_RED    # COLOR OF THE PROMPT FOR ROOT
export CLR_STAFF_PROMPT=$CLR_BRIGHT_GREEN # COLOR OF THE PROMPT FOR STAFF
export CLR_USER_PROMPT=$CLR_BRIGHT_BLUE   # COLOR OF THE PROMPT FOR USERS
export CLR_SSH_PROMPT=$CLR_BRIGHT_MAGENTA # COLOR OF THE PROMPT FOR SSH

# enable colors for various commands
export TERM=xterm-256color
export GREP_OPTIONS='--color=auto'
export GREP_COLOR='1;32'
export CLICOLOR=1

# change ls colors to be more like original unix/linux
export LSCOLORS="ExGxBxDxCxEgEdxbxgxcxd"

# other system settings
export EDITOR='nano'
export HISTCONTROL=ignoredubs
export SVN_EDITOR='${EDITOR}'

# system binds for bash completion
bind "set completion-ignore-case on"     # ignore strict case sensitivity
bind "set bell-style none"               # turn off audible alerts
bind "set show-all-if-ambiguous on"      # show completion with double tap

# turn on advanced completion
if [ -f /etc/bash_completion ]; then
    ./etc/bash_completion
fi

# source scripts
for script in ~/.ssh/scripts/*.sh; do
    source $script
done

# aliases
# -- prompt for overwrites
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

# -- DOS-style shortcuts
alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd .. ; ..'

# -- sudo alias (allow other alias extensions to work when sudo-ing)
alias sudo='sudo '

# shell options
shopt -s checkwinsize     # check window size on script exit
shopt -s cdable_vars      #  enable change directory to a variable value
