#! /usr/bin/env sh

__am_prompt_install_aws() {
	BREWS='awscli aws-sam-cli'

	brew tap aws/tap
	brew update

	for pkg in $BREWS; do
		if brew list --versions "$pkg" 1>/dev/null; then
			print-success "upgrading: $pkg..."
			brew upgrade "$pkg" 2>/dev/null
			brew link --overwrite "$pkg" 2>/dev/null
		else
			print-success "installing: $pkg..."
			brew install "$pkg"
		fi
	done

	print-warn "configuring aws..."
	aws configure
}

__am_prompt_install_aws
