name: end-to-end

on:
  pull_request:
  push:
    branches:
      - build/*
      - master
      - next
      - +([0-9])?(.{+([0-9]),x}).x

jobs:
  cancel:
    name: cancel-previous-runs
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

  os:
    name: "end-to-end-${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    needs: cancel
    strategy:
      matrix:
        os:
          - macos-11.0
          - macos-10.15
          - ubuntu-20.04
          - ubuntu-18.04
          - ubuntu-16.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install-bash
        run: ./install.sh bash | tee log.txt && bash -lc 'cat $AM_PROMPT/.sha'
      - name: install-zsh
        run: ./install.sh zsh | tee log.txt && zsh -lc 'cat $AM_PROMPT/.sha'
      - name: run-tests
        run: ./test.sh

  # TODO: add this after figuring out a consistent way to create a non-root user without having to create specialised
  # dockerfiles for each container type (linuxbrew refuses to install with the root user)
  # docker:
  #   name: "end-to-end-${{ matrix.container }}"
  #   runs-on: ubuntu-20.04
  #   container: ${{ matrix.container }}
  #   needs: cancel
  #   strategy:
  #     matrix:
  #       container:
  #         - centos:7
  #         - centos:8
  #         - debian:9
  #         - debian:10
  #         - fedora:32
  #         - fedora:33
  #         - linuxmintd/mint18-amd64
  #         - linuxmintd/mint19-amd64
  #         - linuxmintd/mint20-amd64
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v2
  #     - name: install-bash
  #       run: ./install.sh bash | tee log.txt && bash -lc 'cat $AM_PROMPT/.sha'
  #     - name: install-zsh
  #       run: ./install.sh zsh | tee log.txt && zsh -lc 'cat $AM_PROMPT/.sha'
  #     - name: run-tests
  #       run: ./test.sh
