name: end-to-end

on:
  pull_request:
  push:
    branches:
      - master
      - next
      - +([0-9])?(.{+([0-9]),x}).x

jobs:
  cancel:
    name: cancel-previous-runs
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

  lint:
    name: lint
    runs-on: ubuntu-20.04
    container: koalaman/shellcheck-alpine:stable
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run-lint
        run: ./hack/lint.sh

  os:
    name: "end-to-end-${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    needs:
      - cancel
      - lint
    strategy:
      matrix:
        os:
          - macos-11.0
          - macos-10.15
          - ubuntu-20.04
          - ubuntu-18.04
          - ubuntu-16.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install-bash
        run: ./hack/install.sh bash
      - name: run-tests-bash
        run: ./hack/test.sh bash
      - name: install-zsh
        run: ./hack/install.sh zsh
      - name: run-tests-zsh
        run: ./hack/test.sh zsh

  win:
    name: "end-to-end-${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    needs:
      - cancel
      - lint
    strategy:
      matrix:
        os:
          - windows-2019
    defaults:
      run:
        shell: wsl-bash {0}
    steps:
      - name: setup-wsl
        uses: vampire/setup-wsl@v1
      - name: checkout
        uses: actions/checkout@v2
      - name: install-pre
        run: ./hack/pre.apt.sh
      - name: install-bash
        run: gosu build ./hack/install.sh bash
      - name: run-tests-bash
        run: gosu build ./hack/test.sh bash
      - name: install-zsh
        run: gosu build ./hack/install.sh zsh
      - name: run-tests-zsh
        run: gosu build ./hack/test.sh zsh

  container-apt:
    name: "end-to-end-${{ matrix.container }}"
    runs-on: ubuntu-20.04
    container: ${{ matrix.container }}
    needs:
      - cancel
      - lint
    strategy:
      matrix:
        container:
          - debian:9
          - debian:10
          - linuxmintd/mint18-amd64
          - linuxmintd/mint19-amd64
          - linuxmintd/mint20-amd64
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install-pre
        run: ./hack/pre.apt.sh
      - name: install-bash
        run: gosu build ./hack/install.sh bash
      - name: run-tests-bash
        run: gosu build ./hack/test.sh bash
      - name: install-zsh
        run: gosu build ./hack/install.sh zsh
      - name: run-tests-zsh
        run: gosu build ./hack/test.sh zsh

  container-yum:
    name: "end-to-end-${{ matrix.container }}"
    runs-on: ubuntu-20.04
    container: ${{ matrix.container }}
    needs:
      - cancel
      - lint
    strategy:
      matrix:
        container:
          - centos:8
          - fedora:32
          - fedora:33
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install-pre
        run: ./hack/pre.yum.sh
      - name: install-bash
        run: gosu build ./hack/install.sh bash
      - name: run-tests-bash
        run: gosu build ./hack/test.sh bash
      - name: install-zsh
        run: gosu build ./hack/install.sh zsh
      - name: run-tests-zsh
        run: gosu build ./hack/test.sh zsh
