name: release

on:
  push:
    branches:
      - master
      - next
      - +([0-9])?(.{+([0-9]),x}).x

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install-node
        uses: actions/setup-node@master

      - name: semantic-release-prerequisites
        run: |
          npm install --no-package-lock --no-save \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator \
            @semantic-release/changelog \
            @semantic-release/exec \
            @semantic-release/github \
            @semantic-release/git

      - name: semantic-release-dry-run
        run: npx semantic-release --ci --dry-run
        if: ${{ github.event.repository.fork }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: semantic-release
        run: npx semantic-release --ci
        if: ${{ !github.event.repository.fork }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
