name: release

on:
  push:
    branches:
      - master
      - next
      - +([0-9])?(.{+([0-9]),x}).x

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install-node
        uses: actions/setup-node@master

      - name: semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
